{% set name = "friendly-traceback" %}
{% set version = "0.7.61" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-traceback-{{ version }}.tar.gz
  sha256: 8ca149ea4effa114a9d4354078d0252dbc53e291cdcc63f23e34b8fb65ba15f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - executing
    - pip
    - python >=3.6
    - tomli
  run:
    - asttokens >=2.0.4
    - executing >=1.1.0
    - pure_eval >=0.2.1
    - python >=3.6
    - six >=1.16
    - stack_data >=0.5.1

test:
  imports:
    - friendly_traceback
    - friendly_traceback.runtime_errors
    - friendly_traceback.syntax_errors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/friendly-traceback/friendly-traceback
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aroberge
    - thewchan
