{% set name = "friendly-traceback" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-traceback-{{ version }}.tar.gz
  sha256: 03f62b1e94ebcfffbf5e86b7863e03b3005ab174267357e4b9be5dd20a346fe0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens >=2.0.4
    - executing >=0.7.0
    - pure_eval >=0.2.1
    - python >=3.6
    - stack_data >=0.1.3

test:
  imports:
    - friendly_traceback
    - friendly_traceback.runtime_errors

about:
  home: https://github.com/friendly-traceback/friendly-traceback
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
