{% set name = "friendly-traceback" %}
{% set version = "0.5.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-traceback-{{ version }}.tar.gz
  sha256: 315f62d186bb627c154c8f171a6e8ba7726f238829df3a6568f600af2b25ff40

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - executing
    - pip
    - pure_eval
    - python >=3.6
  run:
    - asttokens >=2.0.4
    - executing >=0.7.0
    - pure_eval >=0.2.1
    - python >=3.6
    - stack_data >=0.1.3

test:
  imports:
    - friendly_traceback
    - friendly_traceback.runtime_errors
    - friendly_traceback.syntax_errors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/friendly-traceback/friendly-traceback
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
