{% set name = "friendly-traceback" %}
{% set version = "0.7.36" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/friendly-traceback-{{ version }}.tar.gz
  sha256: 2a59d4c41153efabb67063480629d0da74178f4524c99748597f2cf1d4e6b1bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - executing
    - pip
    - python >=3.6
    - tomli
  run:
    - asttokens >=2.0.4
    - executing >=0.8.3
    - pure_eval >=0.2.1
    - python >=3.6
    - stack_data >=0.1.3

test:
  imports:
    - friendly_traceback
    - friendly_traceback.runtime_errors
    - friendly_traceback.syntax_errors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/friendly-traceback/friendly-traceback
  doc_url: https://friendly-traceback.github.io/docs/index.html
  summary: Friendlier tracebacks in any language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
